version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PUSHGATEWAY_URL: "http://pushgateway:9091"
      PORT: 80
    volumes:
      - ./scale_up.sh:/.scale_up.sh
    mem_limit: 50m
    cpus: 0.1
    networks:
      - app-network

  pushgateway:
    image: prom/pushgateway:v1.8.0
    ports:
      - "9091:9091"
    networks:
      - app-network

  nginx:
    image: nginx:1.25.5
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.45.5
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway
#      - app
    networks:
      - app-network

  alertmanager:
    image: prom/alertmanager:v0.24.0
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge