global:
  scrape_interval: 15s

# scrape_configs:
#   - job_name: 'nodejs_app_metrics'
#     static_configs:
#       - targets: ['app:80'] # Указываем целевой хост и порт, где запущено ваше приложение
#     metrics_path: /metrics    # Указываем путь, по которому ваше приложение публикует метрики

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

rule_files:
  - /etc/prometheus/alert.rules.yml